name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Run build.sh
      run: bash build.sh

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Kernel
        path: |
          out/arch/arm64/boot/Image*
          out/arch/arm64/boot/dtbo.img
          out/arch/arm64/boot/*.dtb
